# -*- coding: utf-8 -*-
"""RF_DETR_Aquarium_Object_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bSyrIZGoh_0B80r8I9CeMFn9UBS3xOnb

# RF-DETR Object Detection — Aquarium Dataset

**Final Project: Object Detection System using RF-DETR**

This notebook implements an end-to-end object detection pipeline using **RF-DETR** (Receptive-Field-Enhanced Detection Transformer), a real-time transformer detector developed by Roboflow. It covers:

1. Data acquisition & preparation (Aquarium dataset, COCO format)
2. RF-DETR architecture overview & model setup
3. Training & optimization (AdamW, LR scheduling, early stopping, checkpointing)
4. Evaluation (accuracy, precision, recall, IoU, mAP@0.5)
5. Visualization of predictions
6. Discussion scaffolding (fill in with your own analysis)

> **Note on implementation strategy:** Rather than re-implementing DETR's CNN backbone + transformer encoder-decoder + Hungarian matcher from raw PyTorch (which would take weeks and isn't what the grading rubric is really after), we use Roboflow's open-source `rfdetr` package — a genuine, from-scratch RF-DETR implementation (DINOv2 backbone, deformable transformer encoder-decoder, Hungarian bipartite matching, FFN prediction heads) — and **fine-tune** it on our dataset. This matches the "Adaptation (Recommended)" strategy in the assignment: find an existing implementation and adapt/fine-tune it, rather than building one from zero. Section 2 below maps each required architectural component to where it lives in the library, and you should screenshot the relevant source when writing the report.

## 0. Environment Setup
"""

# Check GPU availability — RF-DETR fine-tuning needs a CUDA GPU.
# In Colab: Runtime > Change runtime type > T4 GPU (free tier) or A100 (Colab Pro)
!nvidia-smi

# Install RF-DETR with training + metrics extras, plus supporting libraries.
!pip install -q "rfdetr[train,metrics]" roboflow "supervision>=0.24.0" pycocotools

"""## 1. Data Acquisition and Preparation

### 1.1 Dataset: Aquarium Dataset (Roboflow Universe)

- **Source:** https://universe.roboflow.com/brad-dwyer/aquarium-combined
- **Images:** 638 (real underwater footage from Roboflow's own aquarium visits)
- **Classes (7):** fish, jellyfish, penguin, puffin, shark, starfish, stingray
- **Annotations:** bounding boxes, COCO JSON format
- **Splits:** the dataset ships pre-split into `train/`, `valid/`, and `test/` folders (~70/20/10), each with its own `_annotations.coco.json`. This satisfies the train/val/test split requirement directly — no manual re-splitting needed, though the code below shows how you'd re-split if your group picks a dataset that isn't already split.

Get a free API key at https://app.roboflow.com/settings/api before running the next cell.

"""

import os
from getpass import getpass

# Paste your Roboflow API key when prompted (kept out of notebook history)
os.environ["ROBOFLOW_API_KEY"] = getpass("Enter your Roboflow API key: ")

from roboflow import Roboflow
from pathlib import Path

rf = Roboflow(api_key=os.environ["ROBOFLOW_API_KEY"])
project = rf.workspace("brad-dwyer").project("aquarium-combined")
dataset = project.version(2).download("coco", location="datasets/aquarium")

DATASET_DIR = Path(dataset.location)
print("Dataset downloaded to:", DATASET_DIR)
print(os.listdir(DATASET_DIR))

# --- OPTIONAL: manual re-splitting template ---
# If your group substitutes a dataset that is NOT pre-split, use this pattern
# (requires: pip install scikit-learn) to create a 70/15/15 split before
# pointing rfdetr at the folders. Skipped here since Aquarium ships pre-split.

# import json, random, shutil
# from sklearn.model_selection import train_test_split
#
# with open("all_annotations.coco.json") as f:
#     coco = json.load(f)
# image_ids = [img["id"] for img in coco["images"]]
# train_ids, temp_ids = train_test_split(image_ids, test_size=0.30, random_state=42)
# val_ids, test_ids = train_test_split(temp_ids, test_size=0.50, random_state=42)
# # then filter coco['images'] / coco['annotations'] by id into 3 new json files

"""### 1.2 Explore the dataset

Before training, inspect class balance and a few annotated samples. This is also useful evidence for the "Dataset Description" section of the report.

"""

import json
import matplotlib.pyplot as plt
from collections import Counter

with open(DATASET_DIR / "train" / "_annotations.coco.json") as f:
    train_coco = json.load(f)

cat_id_to_name = {c["id"]: c["name"] for c in train_coco["categories"]}
class_counts = Counter(cat_id_to_name[ann["category_id"]] for ann in train_coco["annotations"])

print(f"Classes: {list(cat_id_to_name.values())}")
print(f"Train images: {len(train_coco['images'])}")
print(f"Train annotations: {len(train_coco['annotations'])}")

plt.figure(figsize=(8, 4))
plt.bar(class_counts.keys(), class_counts.values(), color="#3b82f6")
plt.title("Training set — instances per class")
plt.ylabel("count")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

import supervision as sv

train_ds = sv.DetectionDataset.from_coco(
    images_directory_path=str(DATASET_DIR / "train"),
    annotations_path=str(DATASET_DIR / "train" / "_annotations.coco.json"),
)
print(f"Loaded {len(train_ds)} training images, classes: {train_ds.classes}")

# Visualize a handful of ground-truth annotated samples
box_annotator = sv.BoxAnnotator()
label_annotator = sv.LabelAnnotator()

fig, axes = plt.subplots(1, 4, figsize=(20, 5))
for ax, idx in zip(axes, [0, 1, 2, 3]):
    _, image, detections = train_ds[idx]
    labels = [train_ds.classes[c] for c in detections.class_id]
    annotated = box_annotator.annotate(image.copy(), detections)
    annotated = label_annotator.annotate(annotated, detections, labels)
    ax.imshow(annotated[:, :, ::-1])  # BGR -> RGB
    ax.axis("off")
plt.suptitle("Ground truth samples — training set")
plt.tight_layout()
plt.show()

"""### 1.3 Preprocessing: resizing, normalization, and augmentation

RF-DETR's `model.train(...)` call handles the standard preprocessing pipeline internally, so your group doesn't need to hand-roll a `Dataset`/`DataLoader` — but you must still understand and report on what it's doing:

- **Resizing:** images are resized to the model's configured input resolution (default 560×560 for `RFDETRBase`) with aspect-ratio-aware padding.
- **Normalization:** pixel values are normalized using ImageNet mean/std statistics, matching the DINOv2 backbone's pretraining distribution.
- **Augmentation:** random horizontal flips, scale jittering, and color jitter are applied automatically during training (this satisfies the "basic data augmentation" requirement). You can pass `resolution=` to `model.train()` to change input size, and increase `epochs` for a stronger augmentation "budget."

The cell below visualizes what one augmented training sample looks like, so you have something concrete to put in the report as evidence of augmentation.

"""

import numpy as np
from PIL import Image
import torchvision.transforms.v2 as T
import torch

# Illustrative augmentation pipeline mirroring what rfdetr applies internally
demo_transform = T.Compose([
    T.RandomHorizontalFlip(p=0.5),
    T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    T.RandomResizedCrop(size=(560, 560), scale=(0.7, 1.0)),
])

_, raw_image_bgr, _ = train_ds[0]
raw_image = Image.fromarray(raw_image_bgr[:, :, ::-1])

fig, axes = plt.subplots(1, 4, figsize=(16, 4))
axes[0].imshow(raw_image); axes[0].set_title("Original"); axes[0].axis("off")
for ax in axes[1:]:
    aug = demo_transform(raw_image)
    ax.imshow(aug); ax.set_title("Augmented"); ax.axis("off")
plt.tight_layout()
plt.show()

"""## 2. RF-DETR Model Implementation

### 2.1 Background: DETR -> RF-DETR

**DETR** (Carion et al., 2020) reframes object detection as direct set prediction:
- A **CNN backbone** extracts spatial feature maps from the image.
- A **Transformer encoder-decoder** attends over these features using a fixed set of learned "object queries," each decoder output corresponding to one predicted object (or "no object").
- A **Hungarian matcher** solves a bipartite matching problem at training time to assign each ground-truth box to exactly one prediction, using a cost that combines classification and box losses. This avoids the need for anchors or non-max suppression.
- **FFN prediction heads** turn each decoder output into a class label and a bounding box (center-x, center-y, width, height).

**RF-DETR** (Robinson, Robicheaux, Popov, Ramanan, Peri — Roboflow, 2025) builds on this with:
- A **DINOv2 vision transformer backbone** instead of a plain CNN, giving stronger, self-supervised pretrained features.
- **Receptive-field enhancement**: multi-scale feature aggregation and a lightweight deformable-attention encoder-decoder (built on Deformable DETR/LW-DETR ideas) so the model can effectively attend to objects at very different scales without the huge compute cost of full global attention — this is the "RF" in RF-DETR, and directly addresses DETR's known weakness on small objects.
- Optimized for a strong **accuracy/latency trade-off**, so the same architecture that gets fine-tuned here can also run in real time.

### 2.2 Where each required component lives in the codebase

| Required component | Where it is in `rfdetr` |
|---|---|
| CNN/backbone | `rfdetr.models.backbone` — DINOv2 ViT backbone |
| Transformer encoder-decoder | `rfdetr.models.transformer` — deformable multi-scale encoder-decoder |
| Receptive Field Enhancement Module | multi-scale feature projection/aggregation layers inside the backbone-to-transformer neck |
| Prediction heads (FFNs) | `rfdetr.models.detr` — classification + bbox regression FFN heads on each decoder layer |
| Hungarian matcher | `rfdetr.models.matcher` — `HungarianMatcher`, used only during training |
| Loss functions | `rfdetr.models.criterion` — classification (focal/CE) loss, L1 box loss, GIoU loss |

"""

# Clone the source so you can screenshot backbone / transformer / matcher / criterion code for your report
!git clone -q https://github.com/roboflow/rf-detr.git /content/rf-detr-source 2>/dev/null || echo "already cloned or clone failed — check network access"
!find /content/rf-detr-source -iname "*matcher*" -o -iname "*criterion*" -o -iname "*backbone*" 2>/dev/null | head -20

from rfdetr import RFDETRBase

# RFDETRBase = the standard-size RF-DETR model, pretrained on COCO.
# Fine-tuning starts from these COCO weights rather than from scratch (transfer learning).
model = RFDETRBase()
print(model)

"""### 2.3 Sanity check: run the COCO-pretrained model before any fine-tuning

Useful to confirm the model loads correctly, and gives you a "before fine-tuning" baseline image to contrast against in your report.

"""

sample_path, sample_image, sample_gt = train_ds[0]
pil_image = Image.fromarray(sample_image[:, :, ::-1])

detections = model.predict(pil_image, threshold=0.5)
print(f"COCO-pretrained model found {len(detections)} objects (classes will be generic COCO classes, not aquarium classes yet)")

"""## 3. Model Training and Optimization

`model.train()` wraps the full training loop: **AdamW** optimizer, a cosine/step **LR scheduler**, **AdamW weight decay**, automatic **EMA (exponential moving average)** weight tracking, **checkpointing**, and optional **early stopping** on validation loss — satisfying the rubric's optimizer / scheduler / early-stopping / checkpointing requirements without you needing to write a manual training loop (though the manual-loop equivalent is sketched afterward for reference/discussion).

Adjust `batch_size` / `grad_accum_steps` to your GPU: keep `batch_size * grad_accum_steps ≈ 16`. On a free Colab T4, `batch_size=4, grad_accum_steps=4` is a safe starting point.

"""

history = []

def log_epoch(data):
    history.append(data)

model.callbacks["on_fit_epoch_end"].append(log_epoch)

model.train(
    dataset_dir=str(DATASET_DIR),
    epochs=30,                 # increase for better convergence; 30 is a reasonable project-scale budget
    batch_size=4,
    grad_accum_steps=4,        # effective batch size = 4 * 4 = 16
    lr=1e-4,                  # AdamW learning rate
    lr_scheduler="cosine",     # cosine LR decay across training
    weight_decay=1e-4,
    early_stopping=True,       # stop early on validation-metric plateau
    early_stopping_patience=5,
    output_dir="/content/rfdetr_output",
    resolution=560,
)

# Plot training / validation loss curves from the logged callback history
import pandas as pd

hist_df = pd.DataFrame(history)
print(hist_df.columns.tolist())  # inspect available logged keys

plt.figure(figsize=(8, 5))
if "train_loss" in hist_df:
    plt.plot(hist_df["train_loss"], label="train loss")
if "val_loss" in hist_df:
    plt.plot(hist_df["val_loss"], label="val loss")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.legend()
plt.title("Training / validation loss")
plt.show()

"""### 3.1 Checkpoints

`model.train()` automatically writes checkpoints into `output_dir`:

- `checkpoint_best_total.pth` — best raw weights by validation metric
- `checkpoint_best_ema.pth` — best EMA-smoothed weights (typically the one to deploy/evaluate)
- `checkpoint_last.pth` — most recent epoch, useful for resuming a crashed run

### 3.2 (Reference) What a manual DETR training loop looks like

Useful for the report's "Training and Optimization" section, to show you understand what `model.train()` is doing under the hood — you do **not** need to run this, since the library already implements it correctly and more efficiently.

"""

"""
Reference-only pseudocode — illustrates the manual loop rfdetr runs internally.
Not executed: rfdetr's train() already implements this (with mixed precision,
distributed training support, EMA, etc.) more robustly than a from-scratch loop would.
"""
# optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
# scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
# best_val_loss, patience_counter = float("inf"), 0
#
# for epoch in range(epochs):
#     model.train()
#     for images, targets in train_loader:
#         outputs = model(images)
#         indices = hungarian_matcher(outputs, targets)          # bipartite matching
#         loss_cls = classification_loss(outputs, targets, indices)
#         loss_bbox = l1_loss(outputs, targets, indices)
#         loss_giou = giou_loss(outputs, targets, indices)
#         loss = loss_cls + 5 * loss_bbox + 2 * loss_giou          # DETR-style weighting
#         loss.backward()
#         optimizer.step(); optimizer.zero_grad()
#     scheduler.step()
#
#     val_loss = evaluate(model, val_loader)
#     if val_loss < best_val_loss:
#         best_val_loss, patience_counter = val_loss, 0
#         torch.save(model.state_dict(), "checkpoint_best.pth")
#     else:
#         patience_counter += 1
#         if patience_counter >= early_stopping_patience:
#             break   # early stopping

"""## 4. Model Evaluation

### 4.1 Load the best fine-tuned checkpoint

"""

from rfdetr import RFDETRBase

best_model = RFDETRBase(pretrain_weights="/content/rfdetr_output/checkpoint_best_ema.pth")

"""### 4.2 IoU, precision, recall, and classification accuracy (custom implementation)



"""

def compute_iou(box_a, box_b):
    """IoU between two boxes in [x1, y1, x2, y2] format."""
    xa1, ya1, xa2, ya2 = box_a
    xb1, yb1, xb2, yb2 = box_b

    inter_x1, inter_y1 = max(xa1, xb1), max(ya1, yb1)
    inter_x2, inter_y2 = min(xa2, xb2), min(ya2, yb2)
    inter_area = max(0.0, inter_x2 - inter_x1) * max(0.0, inter_y2 - inter_y1)

    area_a = max(0.0, xa2 - xa1) * max(0.0, ya2 - ya1)
    area_b = max(0.0, xb2 - xb1) * max(0.0, yb2 - yb1)
    union = area_a + area_b - inter_area

    return inter_area / union if union > 0 else 0.0


def match_detections(pred_boxes, pred_classes, gt_boxes, gt_classes, iou_threshold=0.5):
    """
    Greedy matching (highest-IoU-first) between predictions and ground truth for ONE image.
    Returns counts of TP, FP, FN, and whether each TP had the correct class (for accuracy).
    """
    matched_gt = set()
    tp, fp, correct_class = 0, 0, 0

    # Sort predictions so the most confident/largest-IoU matches happen first (greedy)
    pairs = []
    for pi, pbox in enumerate(pred_boxes):
        for gi, gbox in enumerate(gt_boxes):
            iou = compute_iou(pbox, gbox)
            if iou >= iou_threshold:
                pairs.append((iou, pi, gi))
    pairs.sort(reverse=True, key=lambda x: x[0])

    matched_pred = set()
    for iou, pi, gi in pairs:
        if pi in matched_pred or gi in matched_gt:
            continue
        matched_pred.add(pi)
        matched_gt.add(gi)
        tp += 1
        if pred_classes[pi] == gt_classes[gi]:
            correct_class += 1

    fp = len(pred_boxes) - len(matched_pred)
    fn = len(gt_boxes) - len(matched_gt)
    return tp, fp, fn, correct_class

test_ds = sv.DetectionDataset.from_coco(
    images_directory_path=str(DATASET_DIR / "test"),
    annotations_path=str(DATASET_DIR / "test" / "_annotations.coco.json"),
)

CONF_THRESHOLD = 0.5
IOU_THRESHOLD = 0.5

total_tp = total_fp = total_fn = total_correct_class = 0

for path, image_bgr, gt in test_ds:
    pil_image = Image.fromarray(image_bgr[:, :, ::-1])
    preds = best_model.predict(pil_image, threshold=CONF_THRESHOLD)

    pred_boxes = preds.xyxy.tolist() if len(preds) else []
    pred_classes = preds.class_id.tolist() if len(preds) else []
    gt_boxes = gt.xyxy.tolist()
    gt_classes = gt.class_id.tolist()

    tp, fp, fn, correct = match_detections(pred_boxes, pred_classes, gt_boxes, gt_classes, IOU_THRESHOLD)
    total_tp += tp
    total_fp += fp
    total_fn += fn
    total_correct_class += correct

precision = total_tp / (total_tp + total_fp) if (total_tp + total_fp) else 0.0
recall = total_tp / (total_tp + total_fn) if (total_tp + total_fn) else 0.0
accuracy = total_correct_class / total_tp if total_tp else 0.0   # classification accuracy among matched (TP) boxes

print(f"IoU threshold: {IOU_THRESHOLD}, confidence threshold: {CONF_THRESHOLD}")
print(f"TP={total_tp}  FP={total_fp}  FN={total_fn}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"Classification accuracy (of matched boxes): {accuracy:.4f}")

"""### 4.3 mAP@0.5 and mAP@0.5:0.95 (pycocotools)

For the comprehensive mAP metric, we use `pycocotools`This runs COCO's official evaluation protocol across all classes and IoU thresholds.

"""

import json
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

# Ground truth
coco_gt = COCO(str(DATASET_DIR / "test" / "_annotations.coco.json"))

# Build predictions in COCO results format: list of dicts with image_id, category_id, bbox [x,y,w,h], score
coco_results = []
image_id_lookup = {img["file_name"]: img["id"] for img in coco_gt.dataset["images"]}

for path, image_bgr, gt in test_ds:
    file_name = os.path.basename(path)
    if file_name not in image_id_lookup:
        continue
    image_id = image_id_lookup[file_name]

    pil_image = Image.fromarray(image_bgr[:, :, ::-1])
    preds = best_model.predict(pil_image, threshold=0.01)  # low threshold: let COCOeval do the thresholding

    for box, cls, score in zip(preds.xyxy, preds.class_id, preds.confidence):
        x1, y1, x2, y2 = box
        coco_results.append({
            "image_id": image_id,
            "category_id": int(cls) + 1,  # COCO category ids are typically 1-indexed
            "bbox": [float(x1), float(y1), float(x2 - x1), float(y2 - y1)],
            "score": float(score),
        })

with open("coco_predictions.json", "w") as f:
    json.dump(coco_results, f)

coco_dt = coco_gt.loadRes("coco_predictions.json")
coco_eval = COCOeval(coco_gt, coco_dt, iouType="bbox")
coco_eval.evaluate()
coco_eval.accumulate()
coco_eval.summarize()

print(f"\nmAP@0.5      : {coco_eval.stats[1]:.4f}")
print(f"mAP@0.5:0.95 : {coco_eval.stats[0]:.4f}")

"""### 4.4 Visualize predictions vs. ground truth

Overlay predicted and ground-truth boxes side-by-side on sample test images — direct evidence for the "Visualization" deliverable.

"""

fig, axes = plt.subplots(4, 2, figsize=(14, 22))

for row, idx in enumerate([0, 5, 10, 15]):
    path, image_bgr, gt = test_ds[idx]
    pil_image = Image.fromarray(image_bgr[:, :, ::-1])
    preds = best_model.predict(pil_image, threshold=0.5)

    gt_labels = [test_ds.classes[c] for c in gt.class_id]
    gt_image = box_annotator.annotate(image_bgr.copy(), gt)
    gt_image = label_annotator.annotate(gt_image, gt, gt_labels)

    pred_labels = [f"{test_ds.classes[c]} {conf:.2f}" for c, conf in zip(preds.class_id, preds.confidence)]
    pred_image = box_annotator.annotate(image_bgr.copy(), preds)
    pred_image = label_annotator.annotate(pred_image, preds, pred_labels)

    axes[row, 0].imshow(gt_image[:, :, ::-1]); axes[row, 0].set_title("Ground Truth"); axes[row, 0].axis("off")
    axes[row, 1].imshow(pred_image[:, :, ::-1]); axes[row, 1].set_title("Prediction"); axes[row, 1].axis("off")

plt.tight_layout()
plt.savefig("prediction_visualizations.png", dpi=150)
plt.show()

"""### 4.5 Per-class breakdown (for error analysis)

Repeats the TP/FP/FN matching **per class**, so you can see which classes the model struggles with — critical evidence for the "Error Analysis" section of the report (e.g., you may find small/translucent objects like jellyfish or stingray underperform relative to larger, higher-contrast classes like sharks or penguins).

"""

from collections import defaultdict

per_class_tp = defaultdict(int)
per_class_fp = defaultdict(int)
per_class_fn = defaultdict(int)

for path, image_bgr, gt in test_ds:
    pil_image = Image.fromarray(image_bgr[:, :, ::-1])
    preds = best_model.predict(pil_image, threshold=CONF_THRESHOLD)

    pred_boxes = preds.xyxy.tolist() if len(preds) else []
    pred_classes = preds.class_id.tolist() if len(preds) else []
    gt_boxes = gt.xyxy.tolist()
    gt_classes = gt.class_id.tolist()

    # match per class independently
    for class_id in set(pred_classes) | set(gt_classes):
        p_idx = [i for i, c in enumerate(pred_classes) if c == class_id]
        g_idx = [i for i, c in enumerate(gt_classes) if c == class_id]
        tp, fp, fn, _ = match_detections(
            [pred_boxes[i] for i in p_idx], [class_id] * len(p_idx),
            [gt_boxes[i] for i in g_idx], [class_id] * len(g_idx),
            IOU_THRESHOLD,
        )
        per_class_tp[class_id] += tp
        per_class_fp[class_id] += fp
        per_class_fn[class_id] += fn

print(f"{'Class':<12}{'Precision':<12}{'Recall':<12}")
for class_id in sorted(set(per_class_tp) | set(per_class_fp) | set(per_class_fn)):
    tp, fp, fn = per_class_tp[class_id], per_class_fp[class_id], per_class_fn[class_id]
    p = tp / (tp + fp) if (tp + fp) else 0.0
    r = tp / (tp + fn) if (tp + fn) else 0.0
    print(f"{test_ds.classes[class_id]:<12}{p:<12.3f}{r:<12.3f}")

"""## 5. Discussion of Results

Fill this section in with your group's actual numbers and observations once training completes. Prompts below map directly to the rubric.

**Summary of Metrics**
- Precision: _fill in_
- Recall: _fill in_
- Classification accuracy (matched boxes): _fill in_
- mAP@0.5: _fill in_
- mAP@0.5:0.95: _fill in_

**Performance Analysis** — What do precision vs. recall tell you separately? (e.g., high precision + low recall = model is conservative and misses objects; low precision + high recall = model over-detects.)

**Error Analysis** — Use the per-class table in 4.5 and the visualizations in 4.4: which classes have the lowest precision/recall, and why might that be (e.g., visual similarity between classes, small object size, occlusion by water/glare, class imbalance from 1.2's bar chart)?

**Optimization Impact** — Compare loss curves (3, second cell) and metrics across at least two configurations your group tried (e.g., different `epochs`, `lr`, or `resolution`) to show what your tuning did.

**Limitations** — Dataset size (638 images is small for a transformer model), single-domain images (aquarium tanks only, may not generalize to open ocean), fixed image resolution, etc.

**Future Work** — More epochs / larger RF-DETR variant (`RFDETRMedium`/`RFDETRLarge`), more aggressive augmentation, collecting more diverse images, instance segmentation instead of just boxes (rfdetr supports this natively), deployment/export to ONNX for real-time inference.

## References

- Carion, N., et al. (2020). *End-to-End Object Detection with Transformers (DETR)*. ECCV.
- Zhu, X., et al. (2021). *Deformable DETR: Deformable Transformers for End-to-End Object Detection*. ICLR.
- Robinson, I., Robicheaux, P., Popov, M., Ramanan, D., & Peri, N. (2025). *RF-DETR: Neural Architecture Search for Real-Time Detection Transformers*. Roboflow. https://github.com/roboflow/rf-detr
- Oquab, M., et al. (2023). *DINOv2: Learning Robust Visual Features without Supervision*.
- Lin, T.-Y., et al. (2014). *Microsoft COCO: Common Objects in Context*.
- Roboflow. *Aquarium Dataset*. https://universe.roboflow.com/brad-dwyer/aquarium-combined
"""